import PDFDocument from 'pdfkit-table';
import fs from 'fs';

const doc = new PDFDocument({ margin: 35, size: 'A4' });
const writeStream = fs.createWriteStream('/tmp/test_report.pdf');
doc.pipe(writeStream);

const storeName = 'Cash-n-Carry Superstore';
const title = 'Top Selling Items Report';
const now = new Date();

const dateStr = now.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });

// Top accent bar
doc.rect(35, 30, 525, 4).fill('#4F46E5');

// Left side: Store Name (Bold Stylish Typography)
doc.font('Helvetica-Bold')
   .fontSize(22)
   .fillColor('#0F172A')
   .text(storeName, 35, 44, { width: 340 });

// Left side: Subtitle (smaller size than store name)
doc.font('Helvetica-Bold')
   .fontSize(12)
   .fillColor('#4F46E5')
   .text(title, 35, 72, { width: 340 });

// Right side: Date and Time (Date on top, Time right underneath)
doc.font('Helvetica-Bold')
   .fontSize(9)
   .fillColor('#334155')
   .text(`Date: ${dateStr}`, 380, 48, { width: 180, align: 'right' });

doc.font('Helvetica')
   .fontSize(8.5)
   .fillColor('#64748B')
   .text(`Time: ${timeStr}`, 380, 62, { width: 180, align: 'right' });

// Header separator hairline
doc.moveTo(35, 94)
   .lineTo(560, 94)
   .lineWidth(0.75)
   .strokeColor('#E2E8F0')
   .stroke();

// Mini KPI Summary Cards
doc.roundedRect(35, 108, 165, 48, 6).fillAndStroke('#EEF2FF', '#C7D2FE');
doc.font('Helvetica').fontSize(8).fillColor('#4338CA').text('TOTAL ITEMS TRACKED', 45, 116);
doc.font('Helvetica-Bold').fontSize(16).fillColor('#1E1B4B').text('4 Items', 45, 128);

doc.roundedRect(215, 108, 165, 48, 6).fillAndStroke('#F0FDF4', '#BBF7D0');
doc.font('Helvetica').fontSize(8).fillColor('#15803D').text('TOTAL UNITS SOLD', 225, 116);
doc.font('Helvetica-Bold').fontSize(16).fillColor('#14532D').text('63 Units', 225, 128);

doc.roundedRect(395, 108, 165, 48, 6).fillAndStroke('#FAF5FF', '#E9D5FF');
doc.font('Helvetica').fontSize(8).fillColor('#7E22CE').text('#1 TOP PERFORMER', 405, 116);
doc.font('Helvetica-Bold').fontSize(14).fillColor('#581C87').text('Rice (33 sold)', 405, 128, { width: 145, ellipsis: true });

doc.y = 175;

const table = {
  headers: [
    { label: '#', property: 'idx', width: 45, headerColor: '#4F46E5', headerOpacity: 1, headerAlign: 'center', align: 'center' },
    { label: 'Item Name', property: 'name', width: 330, headerColor: '#4F46E5', headerOpacity: 1, headerAlign: 'left', align: 'left' },
    { label: 'Total Qty Sold', property: 'qty', width: 150, headerColor: '#4F46E5', headerOpacity: 1, headerAlign: 'right', align: 'right' }
  ],
  datas: [
    {
      idx: '1',
      name: 'Rice Super Basmati (5kg)',
      qty: '33 Units',
      options: { backgroundColor: '#F8FAFC', backgroundOpacity: 1 }
    },
    {
      idx: '2',
      name: 'Oats 1kg Premium',
      qty: '15 Units',
      options: { backgroundColor: '#FFFFFF', backgroundOpacity: 1 }
    },
    {
      idx: '3',
      name: 'Daal Maash Washed (1kg)',
      qty: '13 Units',
      options: { backgroundColor: '#F8FAFC', backgroundOpacity: 1 }
    },
    {
      idx: '4',
      name: 'Biscuit Family Pack',
      qty: '2 Units',
      options: { backgroundColor: '#FFFFFF', backgroundOpacity: 1 }
    }
  ]
};

await doc.table(table, {
  x: 35,
  width: 525,
  padding: 8,
  divider: {
    header: { disabled: false, width: 1, opacity: 1, color: '#4338CA' },
    horizontal: { disabled: false, width: 0.5, opacity: 0.25, color: '#CBD5E1' },
    vertical: { disabled: true }
  },
  prepareHeader: () => doc.font('Helvetica-Bold').fontSize(9).fillColor('#FFFFFF'),
  prepareRow: () => doc.font('Helvetica').fontSize(9).fillColor('#1E293B')
});

// Footer at bottom
const bottomY = doc.page.height - 40;
doc.moveTo(35, bottomY - 8)
   .lineTo(560, bottomY - 8)
   .lineWidth(0.5)
   .strokeColor('#CBD5E1')
   .stroke();

doc.font('Helvetica-Bold')
   .fontSize(8)
   .fillColor('#475569')
   .text('Generated by VerbaTask', 35, bottomY, { continued: true });

doc.font('Helvetica')
   .fontSize(8)
   .fillColor('#94A3B8')
   .text('  •  AI-Powered Retail & Inventory Assistant');

doc.font('Helvetica')
   .fontSize(8)
   .fillColor('#94A3B8')
   .text('Confidential Business Report', 380, bottomY, { width: 180, align: 'right' });

doc.end();

writeStream.on('finish', () => {
  console.log('PDF generated successfully at /tmp/test_report.pdf');
});
