import PDFDocument from 'pdfkit-table';
import InventoryItem from '../models/InventoryItem.js';
import Order from '../models/Order.js';

function createPdfBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

/**
 * Builds modern, stylish, branded header and date/time block
 * - Store name: Bold, stylish typography
 * - Subtitle: Smaller size than the store name
 * - Date and Time: Top right corner (Date on top, Time right underneath)
 */
function drawHeader(doc, merchant, title, themeColor = '#4F46E5') {
  const storeName = merchant.businessName || 'My Business Store';
  const now = new Date();

  const dateStr = now.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
  const timeStr = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });

  // Top accent brand line
  doc.rect(35, 30, 525, 4).fill(themeColor);

  // Left: Store name in bold stylish typography
  doc.font('Helvetica-Bold')
    .fontSize(22)
    .fillColor('#0F172A')
    .text(storeName, 35, 44, { width: 340, ellipsis: true });

  // Left: Subtitle in smaller size than the store name
  doc.font('Helvetica-Bold')
    .fontSize(11.5)
    .fillColor(themeColor)
    .text(title, 35, 71, { width: 340 });

  // Right: Date on top, Time directly beneath it
  doc.font('Helvetica-Bold')
    .fontSize(9)
    .fillColor('#334155')
    .text(`Date: ${dateStr}`, 380, 48, { width: 180, align: 'right' });

  doc.font('Helvetica')
    .fontSize(8.5)
    .fillColor('#64748B')
    .text(`Time: ${timeStr}`, 380, 62, { width: 180, align: 'right' });

  // Header separator line
  doc.moveTo(35, 93)
    .lineTo(560, 93)
    .lineWidth(0.75)
    .strokeColor('#E2E8F0')
    .stroke();

  doc.y = 105;
}

/**
 * Renders consistent bottom footer across ALL generated pages.
 * Ensures the footer is placed on the bottom of each page without ever
 * triggering an accidental blank overflow page.
 */
function applyFootersToAllPages(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);

    const origBottomMargin = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;

    const dividerY = doc.page.height - 38;
    const footerY = doc.page.height - 30;

    // Hairline divider
    doc.moveTo(35, dividerY)
      .lineTo(560, dividerY)
      .lineWidth(0.5)
      .strokeColor('#CBD5E1')
      .stroke();

    // Left brand text
    doc.font('Helvetica-Bold')
      .fontSize(8)
      .fillColor('#475569')
      .text('Generated by VerbaTask', 35, footerY, { lineBreak: false });

    doc.font('Helvetica')
      .fontSize(8)
      .fillColor('#94A3B8')
      .text('  •  AI-Powered Retail & Inventory Assistant', 135, footerY, { lineBreak: false });

    // Right page or confidentiality note
    const rightText = range.count > 1
      ? `Page ${i + 1} of ${range.count}`
      : 'Confidential Store Report';

    doc.font('Helvetica')
      .fontSize(8)
      .fillColor('#94A3B8')
      .text(rightText, 380, footerY, { width: 180, align: 'right', lineBreak: false });

    doc.page.margins.bottom = origBottomMargin;
  }
}

/**
 * Draws sleek modern KPI Summary pills
 */
function drawKpiCards(doc, cards, startY = 106) {
  const cardWidth = 165;
  const cardHeight = 52;
  const gap = 15;

  cards.forEach((card, index) => {
    const cardX = 35 + index * (cardWidth + gap);
    doc.roundedRect(cardX, startY, cardWidth, cardHeight, 6)
      .fillAndStroke(card.bgColor, card.borderColor);

    doc.font('Helvetica-Bold')
      .fontSize(7.5)
      .fillColor(card.labelColor)
      .text(card.label.toUpperCase(), cardX + 10, startY + 8);

    const fontSize = card.value && card.value.length > 20 ? 10.5 : 13;
    doc.font('Helvetica-Bold')
      .fontSize(fontSize)
      .fillColor(card.valueColor)
      .text(card.value, cardX + 10, startY + 24, { width: cardWidth - 20, height: 22, ellipsis: true });
  });

  doc.y = startY + cardHeight + 16;
}

export async function generateTopSellingReport(merchant) {
  const doc = new PDFDocument({ margins: { top: 35, bottom: 45, left: 35, right: 35 }, size: 'A4', bufferPages: true });
  drawHeader(doc, merchant, 'Top Selling Items Report', '#4F46E5');

  const pipeline = [
    { $match: { merchantId: merchant._id } },
    { $unwind: '$items' },
    {
      $group: {
        _id: '$items.name',
        totalSold: { $sum: '$items.quantity' },
        revenue: { $sum: '$items.price' },
      },
    },
    { $sort: { totalSold: -1 } },
    { $limit: 20 },
  ];

  const topItems = await Order.aggregate(pipeline);

  const totalSoldAll = topItems.reduce((acc, t) => acc + (t.totalSold || 0), 0);
  const bestSeller = topItems.length > 0 ? `${topItems[0]._id} (${topItems[0].totalSold} sold)` : 'None';

  drawKpiCards(doc, [
    {
      label: 'Ranked Products',
      value: `${topItems.length} Items`,
      bgColor: '#EEF2FF',
      borderColor: '#C7D2FE',
      labelColor: '#4338CA',
      valueColor: '#1E1B4B',
    },
    {
      label: 'Total Volume Sold',
      value: `${totalSoldAll} Units`,
      bgColor: '#F0FDF4',
      borderColor: '#BBF7D0',
      labelColor: '#15803D',
      valueColor: '#14532D',
    },
    {
      label: '#1 Top Bestseller',
      value: bestSeller,
      bgColor: '#FAF5FF',
      borderColor: '#E9D5FF',
      labelColor: '#7E22CE',
      valueColor: '#581C87',
    },
  ]);

  if (topItems.length === 0) {
    doc.font('Helvetica').fontSize(10).fillColor('#64748B').text('No sales data recorded yet to calculate top sellers.');
  } else {
    const table = {
      headers: [
        { label: '#', property: 'idx', width: 45, headerColor: '#4F46E5', headerOpacity: 1, headerAlign: 'center', align: 'center' },
        { label: 'Item Name', property: 'name', width: 330, headerColor: '#4F46E5', headerOpacity: 1, headerAlign: 'left', align: 'left' },
        { label: 'Total Qty Sold', property: 'qty', width: 150, headerColor: '#4F46E5', headerOpacity: 1, headerAlign: 'right', align: 'right' },
      ],
      datas: topItems.map((t, idx) => ({
        idx: (idx + 1).toString(),
        name: t._id || 'Unknown Item',
        qty: `${t.totalSold} Units`,
        options: {
          backgroundColor: idx % 2 === 0 ? '#F8FAFC' : '#FFFFFF',
          backgroundOpacity: 1,
        },
      })),
    };

    await doc.table(table, {
      x: 35,
      width: 525,
      padding: 8,
      divider: {
        header: { disabled: false, width: 1, opacity: 1, color: '#4338CA' },
        horizontal: { disabled: false, width: 0.5, opacity: 0.25, color: '#CBD5E1' },
        vertical: { disabled: true },
      },
      prepareHeader: () => doc.font('Helvetica-Bold').fontSize(9).fillColor('#FFFFFF'),
      prepareRow: () => doc.font('Helvetica').fontSize(9).fillColor('#1E293B'),
    });
  }

  applyFootersToAllPages(doc);
  doc.end();

  return { buffer: await createPdfBuffer(doc), filename: 'Top_Selling_Report.pdf' };
}

export async function generateInventoryReport(merchant) {
  const items = await InventoryItem.find({ merchantId: merchant._id }).sort({ name: 1 });

  const doc = new PDFDocument({ margins: { top: 35, bottom: 45, left: 35, right: 35 }, size: 'A4', bufferPages: true });
  drawHeader(doc, merchant, 'Full Inventory Stock Report', '#2563EB');

  const totalStockQty = items.reduce((acc, i) => acc + (i.quantity || 0), 0);
  const totalValuation = items.reduce((acc, i) => acc + (i.price && i.quantity ? i.price * i.quantity : 0), 0);

  drawKpiCards(doc, [
    {
      label: 'Catalog Items',
      value: `${items.length} Products`,
      bgColor: '#EFF6FF',
      borderColor: '#BFDBFE',
      labelColor: '#1D4ED8',
      valueColor: '#1E3A8A',
    },
    {
      label: 'Total Stock Units',
      value: `${totalStockQty} Units`,
      bgColor: '#F0FDF4',
      borderColor: '#BBF7D0',
      labelColor: '#15803D',
      valueColor: '#14532D',
    },
    {
      label: 'Inventory Valuation',
      value: `PKR ${totalValuation.toLocaleString()}`,
      bgColor: '#FFFBEB',
      borderColor: '#FDE68A',
      labelColor: '#B45309',
      valueColor: '#78350F',
    },
  ]);

  if (items.length === 0) {
    doc.font('Helvetica').fontSize(10).fillColor('#64748B').text('No inventory items logged in your catalog yet.');
  } else {
    const table = {
      headers: [
        { label: '#', property: 'idx', width: 35, headerColor: '#2563EB', headerOpacity: 1, headerAlign: 'center', align: 'center' },
        { label: 'Item Name', property: 'name', width: 220, headerColor: '#2563EB', headerOpacity: 1, headerAlign: 'left', align: 'left' },
        { label: 'Stock Qty', property: 'stock', width: 85, headerColor: '#2563EB', headerOpacity: 1, headerAlign: 'right', align: 'right' },
        { label: 'Unit Price', property: 'price', width: 90, headerColor: '#2563EB', headerOpacity: 1, headerAlign: 'right', align: 'right' },
        { label: 'Total Value', property: 'value', width: 95, headerColor: '#2563EB', headerOpacity: 1, headerAlign: 'right', align: 'right' },
      ],
      datas: items.map((item, idx) => ({
        idx: (idx + 1).toString(),
        name: item.name,
        stock: `${item.quantity} ${item.unit || ''}`.trim(),
        price: item.price ? `Rs. ${item.price}` : '-',
        value: item.price && item.quantity ? `Rs. ${item.price * item.quantity}` : '-',
        options: {
          backgroundColor: idx % 2 === 0 ? '#F8FAFC' : '#FFFFFF',
          backgroundOpacity: 1,
        },
      })),
    };

    await doc.table(table, {
      x: 35,
      width: 525,
      padding: 7,
      divider: {
        header: { disabled: false, width: 1, opacity: 1, color: '#1D4ED8' },
        horizontal: { disabled: false, width: 0.5, opacity: 0.25, color: '#CBD5E1' },
        vertical: { disabled: true },
      },
      prepareHeader: () => doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#FFFFFF'),
      prepareRow: () => doc.font('Helvetica').fontSize(8.5).fillColor('#1E293B'),
    });
  }

  applyFootersToAllPages(doc);
  doc.end();

  return { buffer: await createPdfBuffer(doc), filename: 'Inventory_Report.pdf' };
}

export async function generateLowStockReport(merchant) {
  const items = await InventoryItem.find({ merchantId: merchant._id, quantity: { $lt: 10 } }).sort({ quantity: 1 });

  const doc = new PDFDocument({ margins: { top: 35, bottom: 45, left: 35, right: 35 }, size: 'A4', bufferPages: true });
  drawHeader(doc, merchant, 'Low Stock Alert Report (<10 items)', '#EA580C');

  const criticalCount = items.filter((i) => i.quantity < 5).length;

  drawKpiCards(doc, [
    {
      label: 'Low Stock Alerts',
      value: `${items.length} Items`,
      bgColor: '#FFF7ED',
      borderColor: '#FFEDD5',
      labelColor: '#C2410C',
      valueColor: '#7C2D12',
    },
    {
      label: 'Critical (< 5 left)',
      value: `${criticalCount} Items`,
      bgColor: '#FEF2F2',
      borderColor: '#FECACA',
      labelColor: '#DC2626',
      valueColor: '#7F1D1D',
    },
    {
      label: 'Action Required',
      value: items.length > 0 ? 'Reorder Urgent' : 'Healthy',
      bgColor: '#F0FDF4',
      borderColor: '#BBF7D0',
      labelColor: '#15803D',
      valueColor: '#14532D',
    },
  ]);

  if (items.length === 0) {
    doc.font('Helvetica-Bold').fontSize(11).fillColor('#15803D').text('All stock is healthy! No items are currently below the low stock threshold.');
  } else {
    const table = {
      headers: [
        { label: '#', property: 'idx', width: 45, headerColor: '#EA580C', headerOpacity: 1, headerAlign: 'center', align: 'center' },
        { label: 'Item Name', property: 'name', width: 280, headerColor: '#EA580C', headerOpacity: 1, headerAlign: 'left', align: 'left' },
        { label: 'Remaining Stock', property: 'stock', width: 100, headerColor: '#EA580C', headerOpacity: 1, headerAlign: 'right', align: 'right' },
        { label: 'Urgency', property: 'urgency', width: 100, headerColor: '#EA580C', headerOpacity: 1, headerAlign: 'center', align: 'center' },
      ],
      datas: items.map((item, idx) => ({
        idx: (idx + 1).toString(),
        name: item.name,
        stock: `${item.quantity} ${item.unit || ''}`.trim(),
        urgency: item.quantity <= 3 ? 'CRITICAL' : 'REORDER',
        options: {
          backgroundColor: idx % 2 === 0 ? '#FFF7ED' : '#FFFFFF',
          backgroundOpacity: 1,
        },
      })),
    };

    await doc.table(table, {
      x: 35,
      width: 525,
      padding: 8,
      divider: {
        header: { disabled: false, width: 1, opacity: 1, color: '#C2410C' },
        horizontal: { disabled: false, width: 0.5, opacity: 0.25, color: '#CBD5E1' },
        vertical: { disabled: true },
      },
      prepareHeader: () => doc.font('Helvetica-Bold').fontSize(9).fillColor('#FFFFFF'),
      prepareRow: () => doc.font('Helvetica').fontSize(9).fillColor('#1E293B'),
    });
  }

  applyFootersToAllPages(doc);
  doc.end();

  return { buffer: await createPdfBuffer(doc), filename: 'Low_Stock_Report.pdf' };
}

export async function generateExpiringReport(merchant) {
  const targetExpiry = new Date();
  targetExpiry.setDate(targetExpiry.getDate() + 45);
  const expiryThreshold = `${targetExpiry.getFullYear()}-${String(targetExpiry.getMonth() + 1).padStart(2, '0')}`;

  const items = await InventoryItem.find({ merchantId: merchant._id, expiryDates: { $lte: expiryThreshold } });

  const doc = new PDFDocument({ margins: { top: 35, bottom: 45, left: 35, right: 35 }, size: 'A4', bufferPages: true });
  drawHeader(doc, merchant, 'Expiring Stock Report (Next 45 Days)', '#E11D48');

  const rows = [];
  for (const item of items) {
    const nearingExpiry = item.expiryDates.filter((d) => d <= expiryThreshold).sort();
    if (nearingExpiry.length > 0) {
      rows.push({
        name: item.name,
        dates: nearingExpiry.join(', '),
      });
    }
  }

  drawKpiCards(doc, [
    {
      label: 'Expiring Items',
      value: `${rows.length} Batches`,
      bgColor: '#FFF1F2',
      borderColor: '#FECDD3',
      labelColor: '#BE123C',
      valueColor: '#881337',
    },
    {
      label: 'Monitoring Window',
      value: '45 Days',
      bgColor: '#EFF6FF',
      borderColor: '#BFDBFE',
      labelColor: '#1D4ED8',
      valueColor: '#1E3A8A',
    },
    {
      label: 'Action Suggested',
      value: rows.length > 0 ? 'Discount / Clear' : 'No Action',
      bgColor: '#FDF4FF',
      borderColor: '#F5D0FE',
      labelColor: '#A21CAF',
      valueColor: '#701A75',
    },
  ]);

  if (rows.length === 0) {
    doc.font('Helvetica-Bold').fontSize(11).fillColor('#15803D').text('No stock is nearing expiration in the next 45 days.');
  } else {
    const table = {
      headers: [
        { label: '#', property: 'idx', width: 45, headerColor: '#E11D48', headerOpacity: 1, headerAlign: 'center', align: 'center' },
        { label: 'Item Name', property: 'name', width: 280, headerColor: '#E11D48', headerOpacity: 1, headerAlign: 'left', align: 'left' },
        { label: 'Expiry Batch Dates', property: 'dates', width: 200, headerColor: '#E11D48', headerOpacity: 1, headerAlign: 'left', align: 'left' },
      ],
      datas: rows.map((r, idx) => ({
        idx: (idx + 1).toString(),
        name: r.name,
        dates: r.dates,
        options: {
          backgroundColor: idx % 2 === 0 ? '#FFF1F2' : '#FFFFFF',
          backgroundOpacity: 1,
        },
      })),
    };

    await doc.table(table, {
      x: 35,
      width: 525,
      padding: 8,
      divider: {
        header: { disabled: false, width: 1, opacity: 1, color: '#BE123C' },
        horizontal: { disabled: false, width: 0.5, opacity: 0.25, color: '#CBD5E1' },
        vertical: { disabled: true },
      },
      prepareHeader: () => doc.font('Helvetica-Bold').fontSize(9).fillColor('#FFFFFF'),
      prepareRow: () => doc.font('Helvetica').fontSize(9).fillColor('#1E293B'),
    });
  }

  applyFootersToAllPages(doc);
  doc.end();

  return { buffer: await createPdfBuffer(doc), filename: 'Expiring_Report.pdf' };
}

export async function generateSalesReport(merchant) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const orders = await Order.find({ merchantId: merchant._id, createdAt: { $gte: today } }).sort({ createdAt: -1 });

  const doc = new PDFDocument({ margins: { top: 35, bottom: 45, left: 35, right: 35 }, size: 'A4', bufferPages: true });
  drawHeader(doc, merchant, 'Daily Sales Report (Today)', '#059669');

  let totalRevenue = 0;
  const datas = orders.map((o, idx) => {
    const amt = o.total || 0;
    totalRevenue += amt;
    return {
      time: new Date(o.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      items: o.items.map((i) => `${i.quantity}x ${i.name}`).join(', '),
      payment: (o.paymentMethod || 'cash').toUpperCase(),
      amount: `Rs. ${amt}`,
      options: {
        backgroundColor: idx % 2 === 0 ? '#F0FDF4' : '#FFFFFF',
        backgroundOpacity: 1,
      },
    };
  });

  const avgOrder = orders.length > 0 ? Math.round(totalRevenue / orders.length) : 0;

  drawKpiCards(doc, [
    {
      label: 'Orders Logged Today',
      value: `${orders.length} Orders`,
      bgColor: '#ECFDF5',
      borderColor: '#A7F3D0',
      labelColor: '#047857',
      valueColor: '#064E3B',
    },
    {
      label: 'Today Total Revenue',
      value: `PKR ${totalRevenue.toLocaleString()}`,
      bgColor: '#EFF6FF',
      borderColor: '#BFDBFE',
      labelColor: '#1D4ED8',
      valueColor: '#1E3A8A',
    },
    {
      label: 'Average Order Value',
      value: `PKR ${avgOrder.toLocaleString()}`,
      bgColor: '#FAF5FF',
      borderColor: '#E9D5FF',
      labelColor: '#7E22CE',
      valueColor: '#581C87',
    },
  ]);

  if (orders.length === 0) {
    doc.font('Helvetica').fontSize(10).fillColor('#64748B').text('No sales have been recorded for today yet.');
  } else {
    const table = {
      headers: [
        { label: 'Time', property: 'time', width: 65, headerColor: '#059669', headerOpacity: 1, headerAlign: 'left', align: 'left' },
        { label: 'Items Ordered', property: 'items', width: 270, headerColor: '#059669', headerOpacity: 1, headerAlign: 'left', align: 'left' },
        { label: 'Payment', property: 'payment', width: 95, headerColor: '#059669', headerOpacity: 1, headerAlign: 'center', align: 'center' },
        { label: 'Amount (PKR)', property: 'amount', width: 95, headerColor: '#059669', headerOpacity: 1, headerAlign: 'right', align: 'right' },
      ],
      datas,
    };

    await doc.table(table, {
      x: 35,
      width: 525,
      padding: 7,
      divider: {
        header: { disabled: false, width: 1, opacity: 1, color: '#047857' },
        horizontal: { disabled: false, width: 0.5, opacity: 0.25, color: '#CBD5E1' },
        vertical: { disabled: true },
      },
      prepareHeader: () => doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#FFFFFF'),
      prepareRow: () => doc.font('Helvetica').fontSize(8.5).fillColor('#1E293B'),
    });
  }

  applyFootersToAllPages(doc);
  doc.end();

  return { buffer: await createPdfBuffer(doc), filename: 'Daily_Sales_Report.pdf' };
}
